In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(4,4))

In [3]:
arr

array([[9, 4, 3, 4],
       [2, 1, 8, 8],
       [3, 1, 6, 5],
       [9, 4, 8, 7]])

In [4]:
arr.reshape(8,2)

array([[9, 4],
       [3, 4],
       [2, 1],
       [8, 8],
       [3, 1],
       [6, 5],
       [9, 4],
       [8, 7]])

In [5]:
arr.T

array([[9, 2, 3, 9],
       [4, 1, 1, 4],
       [3, 8, 6, 8],
       [4, 8, 5, 7]])

In [6]:
arr.flatten()

array([9, 4, 3, 4, 2, 1, 8, 8, 3, 1, 6, 5, 9, 4, 8, 7])

In [7]:
arr

array([[9, 4, 3, 4],
       [2, 1, 8, 8],
       [3, 1, 6, 5],
       [9, 4, 8, 7]])

In [10]:
np.expand_dims(arr,axis=1)

array([[[9, 4, 3, 4]],

       [[2, 1, 8, 8]],

       [[3, 1, 6, 5]],

       [[9, 4, 8, 7]]])

In [11]:
data=np.array([[1],[2],[3]])

In [12]:
np.squeeze(data)

array([1, 2, 3])

In [13]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [14]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [15]:
arr=np.array(["sudh","kumar"])

In [16]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [17]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [18]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [19]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [21]:
np.mean(arr1)

NameError: name 'arr1' is not defined

In [22]:
arr=np.random.randint(1,10,(4,4))

In [24]:
np.mean(arr)

5.5

In [25]:
np.cos(arr)

array([[-0.65364362,  0.75390225, -0.14550003, -0.9899925 ],
       [-0.14550003,  0.96017029,  0.28366219,  0.96017029],
       [ 0.75390225, -0.9899925 , -0.14550003, -0.9899925 ],
       [-0.91113026,  0.75390225, -0.9899925 ,  0.54030231]])

In [26]:
np.tan(arr)

array([[ 1.15782128,  0.87144798, -6.79971146, -0.14254654],
       [-6.79971146, -0.29100619, -3.38051501, -0.29100619],
       [ 0.87144798, -0.14254654, -6.79971146, -0.14254654],
       [-0.45231566,  0.87144798, -0.14254654,  1.55740772]])

In [27]:
np.exp(arr)

array([[5.45981500e+01, 1.09663316e+03, 2.98095799e+03, 2.00855369e+01],
       [2.98095799e+03, 4.03428793e+02, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.00855369e+01, 2.98095799e+03, 2.00855369e+01],
       [8.10308393e+03, 1.09663316e+03, 2.00855369e+01, 2.71828183e+00]])

In [28]:
np.power(arr,2)

array([[16, 49, 64,  9],
       [64, 36, 25, 36],
       [49,  9, 64,  9],
       [81, 49,  9,  1]])

In [29]:
np.mean(arr)

5.5

In [30]:
np.median(arr)

6.0

In [31]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

In [32]:
np.std(arr)

2.318404623873926

In [33]:
np.var(arr)

5.375

In [34]:
np.min(arr)

1

In [35]:
np.max(arr)

9

In [36]:
arr1=np.random.randint(1,10,(4,4))
arr2=np.random.randint(11,20,(4,4))

In [37]:
arr1-arr2

array([[ -9, -13, -12, -12],
       [-17, -12,  -5, -14],
       [-13,  -7, -13, -14],
       [-11,  -3,  -7, -10]])

In [38]:
np.multiply(arr1,arr2)

array([[112,  68,  85, 133],
       [ 18,  64, 104,  15],
       [ 30,  44,  14,  95],
       [ 26, 108,  78,  96]])

In [39]:
np.power(arr1,arr2)

array([[   33232930569601,       17179869184,      762939453125,
        11398895185373143],
       [                1,        4294967296,      549755813888,
                        1],
       [            32768,           4194304,                 1,
           19073486328125],
       [             8192,      282429536481,       13060694016,
            2821109907456]])

In [40]:
np.sqrt(arr1)

array([[2.64575131, 2.        , 2.23606798, 2.64575131],
       [1.        , 2.        , 2.82842712, 1.        ],
       [1.41421356, 2.        , 1.        , 2.23606798],
       [1.41421356, 3.        , 2.44948974, 2.44948974]])