In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
np.arange(.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [5]:
list(np.arange(.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [7]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.zeros((3,4,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
arr=np.ones((3,4))

In [17]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [19]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr1=np.eye(5)

In [22]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [23]:
np.random.rand(2,3)

array([[0.86269069, 0.71280873, 0.72559353],
       [0.52518759, 0.89928939, 0.20697722]])

In [24]:
np.random.randn(2,3)

array([[-1.07563778,  2.10705786, -0.05831152],
       [-0.20760462,  1.47790044,  0.91140618]])

In [26]:
arr2=np.random.randint(1,5,(3,4))

In [27]:
arr2

array([[2, 4, 4, 2],
       [1, 2, 1, 1],
       [4, 4, 2, 2]])

In [28]:
arr2.size

12

In [29]:
arr2.shape

(3, 4)

In [30]:
arr2.reshape(6,2)

array([[2, 4],
       [4, 2],
       [1, 2],
       [1, 1],
       [4, 4],
       [2, 2]])

In [31]:
arr2 >8

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [32]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr1[2:4,[2,3]]

array([[1., 0.],
       [0., 1.]])

In [36]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [37]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [38]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [39]:
arr1+arr2

array([[2, 3, 2],
       [2, 4, 3],
       [4, 4, 2]])