In [1]:
import numpy as np

In [4]:
arr=np.array([4,5,2,1,7,2,3])

In [6]:
arr

array([4, 5, 2, 1, 7, 2, 3])

In [5]:
np.sort(arr)

array([1, 2, 2, 3, 4, 5, 7])

In [8]:
np.searchsorted(arr,6)

7

In [10]:
arr1=np.array([0,2,0,1,4,5,2,0,41,5,4,0,0,0,5])

In [11]:
np.count_nonzero(arr1)

9

In [12]:
np.where(arr1>0)

(array([ 1,  3,  4,  5,  6,  8,  9, 10, 14]),)

In [13]:
np.extract(arr1 >2 ,arr1)

array([ 4,  5, 41,  5,  4,  5])

In [14]:
a=np.copy(arr1)

In [15]:
a

array([ 0,  2,  0,  1,  4,  5,  2,  0, 41,  5,  4,  0,  0,  0,  5])

In [16]:
arr1

array([ 0,  2,  0,  1,  4,  5,  2,  0, 41,  5,  4,  0,  0,  0,  5])

In [17]:
b=arr.view()

In [18]:
b

array([4, 5, 2, 1, 7, 2, 3])

In [19]:
b[0]=234

In [20]:
b

array([234,   5,   2,   1,   7,   2,   3])

In [21]:
import numpy.matlib as nm

In [22]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [23]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
nm,eye(4)

NameError: name 'eye' is not defined

In [25]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [26]:
arr2=np.random.randint(2,5,(4,5))

In [27]:
arr1

array([ 0,  2,  0,  1,  4,  5,  2,  0, 41,  5,  4,  0,  0,  0,  5])

In [28]:
arr2

array([[2, 2, 3, 3, 3],
       [3, 3, 4, 4, 3],
       [2, 3, 4, 2, 2],
       [3, 3, 3, 2, 4]])

In [29]:
arr3=np.random.randint(2,5,(4,5))

In [30]:
arr3

array([[2, 3, 2, 2, 2],
       [4, 2, 3, 2, 4],
       [2, 4, 2, 2, 3],
       [4, 4, 2, 3, 4]])

In [32]:
np.dot(arr2,arr3)

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [33]:
np.dot((arr2,arr3))

TypeError: dot() missing 1 required positional argument: 'b'