In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.ndim

2

In [11]:
mat=np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a=arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0]=100

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [23]:
list(i*i for i in range (5))

[0, 1, 4, 9, 16]

In [24]:
iterable=(i*i for i in range (5))

In [26]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
np.fromstring('23 22 33 44 66 77',sep=" ")

array([23., 22., 33., 44., 66., 77.])

In [28]:
np.fromstring('23,22,33,44,66,77',sep=",")

array([23., 22., 33., 44., 66., 77.])

In [29]:
arr

array([100,   2,   3,   4,   5])

In [30]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr.ndim


1

In [32]:
arr1.ndim

2

In [33]:
arr.size

5